stages:
  - build
  - deploy

build-Backend-STAGING:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - apt-get update -qy
    - apt-get install -y openssh-client
    - apt-get install -y sshpass
    - cd LoveStory.Backend
  script:
    - dotnet restore
    - dotnet publish -c Release -o out
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_ACCOUNT@stg-lovestory-api.coreop.local "powershell.exe Stop-Website -Name stg-lovestory"
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r out $SSH_ACCOUNT@$STAGING_BACKEND_DEPLOY_PATH
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_ACCOUNT@stg-lovestory-api.coreop.local "powershell.exe Start-Website -Name stg-lovestory"
  tags:
    - dotnet8
  
build-Frontend-STAGING:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  before_script:
    - apt-get update -qy
    - apt-get install -y openssh-client
    - apt-get install -y sshpass 
    - apt-get install -y unzip 
    - curl -fsSL https://bun.sh/install | bash
    - echo 'export PATH="$HOME/.bun/bin:$PATH"' >> ~/.bashrc
    - source ~/.bashrc
    - cd LoveStory.Frontend
  script:
    - sed -i 's/=BACKEND_SERVICE_BASE_API_ADDRESS/=$STG_BACKEND_SERVICE_BASE_API_ADDRESS/g' .env.staging
    - bun install && bun run build:staging
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r .output $SSH_ACCOUNT@$STAGING_FRONTEND_DEPLOY_PATH
  tags:
    - dotnet8